openapi: 3.0.0
info:
  title: Book API
  version: "1.0"
  description: API для работы с книгами.

paths:
  /api/books:
    get:
      summary: Получить список всех книг
      responses:
        "200":
          description: Список всех книг
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Добавить новую книгу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        "201":
          description: Книга успешно добавлена
        "400":
          description: Ошибка валидации
  /api/books/{book_id}:
    get:
      summary: Получить книгу по ID
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Книга найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        "404":
          description: Книга не найдена

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "A Byte of Python"
        author:
          type: string
          example: "Swaroop C. H."
