[uwsgi]
wsgi-file = /home/simon/PycharmProjects/python_advanced/module_23_cgi_server/homework/hw_3/app.py
master = true
module = app:app
processes = 5
socket = /run/uwsgi.sock
chmod-socket = 660
vacuum = true
die-on-term = true
