[uwsgi]
wsgi-file = /home/simon/PycharmProjects/python_advanced/module_23_cgi_server/homework/hw_2/routes.py
socket = /run/uwsgi.sock
chown-socket = www-data:www-data
chmod-socket = 664
# for debugging
show-config = true
# Доп.параметры которые я нашел
master = true  # мастер-процесс
processes = 5  # Количество рабочих процессов
vacuum = true  # Удаляет сокет при остановке
die-on-term = true  # Завершает uWSGI при получении SIGTERM, для управления процессами